-- BMW.BMW_SALES.BMW_SALESDATUSE DATABASE BMW;
USE SCHEMA BMW_SALES;


------ 1️⃣ Data Exploration


-- Lists all tables.
SHOW TABLES;

-- Preview Sample rows.

SELECT * FROM SALESDATA
LIMIT 10;

--- Check for Missing Values

SELECT * FROM SALESDATA
WHERE CAR_MODEL IS NULL OR 
YEAR IS NULL OR
REGION IS NULL OR
COLOR IS NULL OR
FUEL_TYPE IS NULL OR
VEHICLE_TYPE IS NULL OR
TRANSMISSION IS NULL OR
ENGINE_SIZE_L IS NULL OR
MILEAGE_KM IS NULL OR
MILEAGE_RANGE IS NULL OR
PRICE_RANGE IS NULL OR
PRICE_USD IS NULL OR
SALES_VOLUME IS NULL OR
SALES_CLASSIFICATION IS NULL;

--- Count Unique Car Models

SELECT COUNT(DISTINCT(CAR_MODEL)) AS CAR_MODEL FROM SALESDATA;

--- Car Model Distribution

SELECT DISTINCT(CAR_MODEL) AS CAR_MODEL , COUNT(*) AS TOTAL FROM SALESDATA
GROUP BY CAR_MODEL
ORDER BY TOTAL DESC;

--- Count Unique Regions

SELECT COUNT(DISTINCT REGION) AS REGION FROM SALESDATA;

--- Region Distribution

SELECT DISTINCT(REGION) AS REGION , COUNT(*) AS TOTAL FROM SALESDATA
GROUP BY REGION
ORDER BY TOTAL DESC;




------ 📊 Sales & Market Performance

-- Which BMW models have been the top sellers from 2010–2024?

SELECT CAR_MODEL , SUM(SALES_VOLUME) AS SALES , YEAR FROM SALESDATA
GROUP BY CAR_MODEL , YEAR
ORDER BY SALES DESC
LIMIT 5;


-- How have BMW sales trended year-over-year (growth or decline)?

SELECT YEAR, SUM(SALES_VOLUME) AS TOTAL_SALES FROM SALESDATA
GROUP BY YEAR
ORDER BY YEAR ASC;


-- Which regions (Asia, Europe, North America, etc.) contribute the most to total BMW sales?

SELECT REGION , SUM(SALES_VOLUME) AS TOTAL_SALES FROM SALESDATA
GROUP BY REGION 
ORDER BY TOTAL_SALES DESC;


-- Which car color is the most popular among buyers across different regions?

SELECT REGION ,COLOR, TOTAL_SALES FROM ( SELECT COLOR , REGION , SUM(SALES_VOLUME) AS TOTAL_SALES , RANK() OVER (PARTITION BY REGION ORDER BY SUM(SALES_VOLUME) DESC) AS RANKING FROM SALESDATA
GROUP BY COLOR, REGION ) AS RANKED_SALES
WHERE RANKING = 1
ORDER BY TOTAL_SALES DESC;


-- What is the distribution of sales between Petrol, Diesel, Hybrid, and Electric cars?

SELECT FUEL_TYPE , SUM(SALES_VOLUME) AS TOTAL_SALES FROM SALESDATA
GROUP BY FUEL_TYPE
ORDER BY TOTAL_SALES;


------ 💰 Revenue & Pricing Insights

-- What is the average selling price (USD) for BMW cars in each region?

SELECT CAR_MODEL, REGION , AVG_SP, RANKING FROM (
SELECT CAR_MODEL, REGION, ROUND(AVG(PRICE_USD),1) AS AVG_SP, RANK() OVER (PARTITION BY REGION ORDER BY AVG(PRICE_USD) DESC) AS RANKING FROM SALESDATA
GROUP BY CAR_MODEL , REGION) AS RANKED_SALES
WHERE RANKING = 1;


-- Which BMW models fall mostly into the “High Price” range vs. “Medium” vs. “Low”?

SELECT CAR_MODEL , PRICE_RANGE,TOTAL, RANKING FROM (
SELECT CAR_MODEL , COUNT(*) AS TOTAL, PRICE_RANGE, RANK() OVER (PARTITION BY PRICE_RANGE ORDER BY COUNT(*) DESC) AS RANKING FROM SALESDATA
GROUP BY CAR_MODEL ,PRICE_RANGE ) AS RANKED_SALES
WHERE RANKING = 1;


-- How are sales distributed across regions and price categories?

SELECT REGION , PRICE_RANGE , SUM(SALES_VOLUME) AS SALES FROM SALESDATA
GROUP BY REGION, PRICE_RANGE
ORDER BY SALES DESC;


-- Are higher-priced models selling more in certain regions compared to others?

SELECT REGION , PRICE_RANGE , SALES, RANKING FROM(
SELECT REGION , PRICE_RANGE , SUM(SALES_VOLUME) AS SALES , RANK() OVER (PARTITION BY REGION ORDER BY SUM(SALES_VOLUME) DESC) AS RANKING FROM SALESDATA
GROUP BY REGION , PRICE_RANGE) AS RANKED_SALES
WHERE RANKING = 1;


-- How does sales volume differ between low, medium, and high price categories?

SELECT SUM(SALES_VOLUME) AS SALES , PRICE_RANGE FROM SALESDATA
GROUP BY PRICE_RANGE
ORDER BY SALES;


------ 🚗 Product & Customer Preferences

-- Do customers prefer Automatic or Manual transmission cars overall?

SELECT  TRANSMISSION, COUNT(*) AS CARS FROM SALESDATA
GROUP BY TRANSMISSION
ORDER BY CARS DESC;


-- Which engine sizes (e.g., 2.0L, 3.0L, 4.0L) are most popular with buyers?

SELECT COUNT(*) AS CARS , ENGINE_SIZE_L FROM SALESDATA
GROUP BY ENGINE_SIZE_L
ORDER BY CARS DESC
LIMIT 5;


-- Is there a trend where lower mileage cars are sold at higher prices?

SELECT CASE WHEN MILEAGE_KM <= 20000 THEN '0-20K'
            WHEN MILEAGE_KM <= 40000 THEN '20-40K'
            WHEN MILEAGE_KM <= 60000 THEN '40-60K'
            WHEN MILEAGE_KM <= 80000 THEN '60-80K'
        ELSE '80K+'
        END AS MILEAGE_BUCKET ,

    PRICE_RANGE ,ROUND(AVG(PRICE_USD),2) AS AVG_SP FROM SALESDATA
GROUP BY MILEAGE_BUCKET , PRICE_RANGE 
ORDER BY CASE WHEN MILEAGE_BUCKET = '0-20K' THEN 1 
              WHEN MILEAGE_BUCKET = '20-40K' THEN 2
              WHEN MILEAGE_BUCKET = '40-60K' THEN 3
              WHEN MILEAGE_BUCKET = '60-80K' THEN 4
        ELSE 5
        END;

        
-- How does mileage range (Low/Medium/High) affect sales classification (High vs Low)?

SELECT COUNT(*) AS CARS, MILEAGE_RANGE , SALES_CLASSIFICATION FROM SALESDATA
GROUP BY MILEAGE_RANGE,SALES_CLASSIFICATION
ORDER BY CARS DESC;


------ 📈 Strategic & Forecasting

-- Which regions are showing the fastest growth in BMW sales over the years?
SELECT REGION , YEAR , TOTAL_SALES ,
TOTAL_SALES - LAG(TOTAL_SALES) OVER (PARTITION BY REGION ORDER BY YEAR) AS GROWTH FROM
(SELECT REGION , YEAR ,COUNT(*) AS TOTAL_SALES FROM SALESDATA
GROUP BY REGION , YEAR 
) AS YEARLY_SALES
ORDER BY GROWTH DESC;


-- What is the sales trend for Hybrid/Electric vehicles — is adoption increasing or flat?

SELECT FUEL_TYPE , TOTAL_SALES , YEAR,
TOTAL_SALES - LAG(TOTAL_SALES) OVER (PARTITION BY FUEL_TYPE ORDER BY YEAR) AS GROWTH,
ROUND(
((TOTAL_SALES - LAG(TOTAL_SALES) OVER (PARTITION BY FUEL_TYPE ORDER BY YEAR)) / LAG(TOTAL_SALES) OVER (PARTITION BY FUEL_TYPE ORDER BY YEAR)
)*100 ,2) AS GROWTH_PERCENT
FROM (
SELECT FUEL_TYPE,  SUM(SALES_VOLUME) AS TOTAL_SALES ,  YEAR FROM SALESDATA
GROUP BY FUEL_TYPE ,  YEAR) AS YEARLY_SALES
WHERE FUEL_TYPE IN ('Hybrid', 'Electric')
ORDER BY GROWTH DESC , YEAR ASC;



SELECT DISTINCT CAR_MODEL FROM SALESDATA;
